### ISSUE TITLE
Use Driver or BehaviorRelay

### ISSUE THREAD

**Issue by ClegeJJ** [khoren93/SwiftHub#10]
Why RepositoriesViewModel.Output.items use BehaviorRelay,but ThemeViewModel.Output.items use Driver?  
 
I am studying RxSwift, Thank you.

**Comment by khoren93** [comment]
Hi @ClegeJJ 

I fixed this, now items has Driver type :)
You can check this links (Variable is deprecated in favor of BehaviorRelay)
https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Traits.md#driver
https://github.com/ReactiveX/RxSwift/issues/487

Thanks.

**Comment by ClegeJJ** [comment]
Thank you very much.
