### ISSUE TITLE
Firebase plist in repo

### ISSUE THREAD

**Issue by DanBurkhardt** [khoren93/SwiftHub#12]
Hey just want to let you know that your Firebase plist is included in your Repo. Not sure if you have anything critical in there but it could be exposing any DB contents you have or access to your services. Thanks for contributing this great work, looking forward to playing around with it.

**Comment by khoren93** [comment]
Hi @DanBurkhardt 

I created two firebase applications, one for developmet and one for App Store.
The project also contains keys for these services which will also be replaced in the release.

    enum Keys {
        case github, mixpanel, adMob
    }

https://github.com/khoren93/SwiftHub/issues/11
Thanks :)

**Comment by DanBurkhardt** [comment]
Reading this on a locally built/run version right now! Thanks man.
