### ISSUE TITLE
Home load more footer animation is unnormal

### ISSUE THREAD

**Issue by qiuncheng** [khoren93/SwiftHub#13]
**Describe the bug**
When downloaded from App Store with not login status, pull up on home page, the footer refresh animation will not show, as the gif shows:
**To Reproduce**
1. Go to 'Home Page'
2. Scroll down to `load more'
3. See error

**Expected behavior**
It should animate footer naturally

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9990834/53971183-5ebd9400-4137-11e9-85c5-7efc94e46d83.gif)

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Version [e.g. 1.6.0 App Store]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS12.1.4]

**Comment by khoren93** [comment]
Hi @qiuncheng 
I fixed this issue, please check out.
Thanks!

**Comment by qiuncheng** [comment]
Awesome, it's gone, Thx
