### ISSUE TITLE
var largeTitleTextAttributes: Binder<[NSAttributedString.Key: Any]?>

### ISSUE THREAD

**Issue by gorbat-o** [khoren93/SwiftHub#17]
Hey, 

I tried to use this new binder you created in an extension of UINavigationBar
`var largeTitleTextAttributes: Binder<[NSAttributedString.Key: Any]?>`

When I am trying to bind something on it it says `Property 'largeTitleTextAttributes' requires that 'UINavigationItem' inherit from 'UINavigationBar'` 
do you have any ideas why it wouldn't work?

Thank you!

**Comment by khoren93** [comment]
Hi @gorbat-o 
Try this in NavigationController.swift :)
```
  navigationBar.prefersLargeTitles = true
  themeService.rx
      .bind({ [NSAttributedString.Key.foregroundColor: $0.text] }, to: navigationBar.rx.largeTitleTextAttributes)
      .disposed(by: rx.disposeBag)
```

**Comment by gorbat-o** [comment]
Thank you for your fast reply, I just succeeded to make it work, I completely forgot to put it in the `NavigationController` class. (I was trying in my `ViewController` class) 😂😅

Thanks again, I think I need to sleep haha
