### ISSUE TITLE
bundle exec fastlane setup failed

### ISSUE THREAD

**Issue by tospery** [khoren93/SwiftHub#18]
[17:26:23]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/usr/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command 'brew install node' was 1 instead of 0.
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

**Comment by khoren93** [comment]
Hi @tospery 
I updated the project [building instructions](https://github.com/khoren93/SwiftHub#building-and-running), please clone project and try again.
Thanks!
