### ISSUE TITLE
Render markdown

### ISSUE THREAD

**Issue by CraKeyBoy** [khoren93/SwiftHub#19]
**Is your feature request related to a problem? Please describe.**
I have used this awesome App,  but I found the markdown file not render. 

**Describe the solution you'd like**
Can you add the feature for markdown file render?

**Describe alternatives you've considered**

**Additional context**
If App can render markdown file and add a toc. It will be perfect.

**Comment by khoren93** [comment]
Hi @javmain 
I tried to integrate several libraries for rendering Markdown, but none of them worked well enough. 
I will try to add this feature in future versions when I find the applicable solution.
Thanks.

**Comment by javmain** [comment]
Thanks a lot.
