### ISSUE TITLE
get started failed...

### ISSUE THREAD

**Issue by Lorwy** [khoren93/SwiftHub#2]
![image](https://user-images.githubusercontent.com/6788741/48710267-b5639880-ec42-11e8-8511-0860f265245b.png)

**Comment by SilenceZhou** [comment]
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to kit-downloads.fabric.io:443

**Comment by tibinthomas9** [comment]
Hi @khoren93 ,
What is bundler and why use it instead of cocoapods?

**Comment by khoren93** [comment]
Hi @tibinthomas9 ,
Bundler provides a consistent environment for Ruby projects by tracking and installing the exact gems and versions that are needed. 
In this project i used bundler (Gemfile) to easy install Cocoapods and Fastlane with one command.
https://bundler.io
