### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by liujunliuhong** [khoren93/SwiftHub#22]
I am running the app and it crashes. What should I do?
![image](https://user-images.githubusercontent.com/16097707/62773340-81801a00-bad4-11e9-87e6-50f07d081813.png)

**Comment by khoren93** [comment]
Hi @liujunliuhong 
I updated the project [building instructions](https://github.com/khoren93/SwiftHub#building-and-running), please clone project and try again.
Thanks!
