### ISSUE TITLE
Some icons purpose is hard to understand

### ISSUE THREAD

**Issue by jmmunoz14** [khoren93/SwiftHub#26]
**Is your feature request related to a problem? Please describe.**
Some icons (Snapshot below) are hard to understand, i had to press them and take a moment to see what changed to understand what was their purpose. 

![image](https://user-images.githubusercontent.com/25345635/69487976-ae60fe80-0e31-11ea-8e1c-0636fbbdffef.png)
 

**Describe the solution you'd like**
Perhaps a hover text with a description should be created when the user holds an icon.

**Describe alternatives you've considered**
text fields below the icons describing their use.

**Comment by khoren93** [comment]
Hi @jmmunoz14 
I added titles under segment icons, thanks for Your feedback))
