### ISSUE TITLE
Eventual Connectivity Management

### ISSUE THREAD

**Issue by jhlake** [khoren93/SwiftHub#28]
**Is your feature request related to a problem? Please describe.**
We were using the app and decided to test how it reacted to loss of internet mid use. If we suddenly lost internet connection, there was no feedback.

**Describe the solution you'd like**
We suggest to add a constant Network Manager (a singleton class) that informs the user when he is out of internet. This is just as a reminder, because if a user tries to use the app but doesn’t have internet, he could be waiting forever for it to load.

**Describe alternatives you've considered**
We developed a version that works for our apps in Swift 5.0. We tried implementing it in SwiftHub to do a Pull Request but since it’s Swift 4.0, it had some issues. I’m adding some screenshots of our solution. The “Toast” class is simply a way to present messages in a Toast fashion like Android.

**Additional context**
![WhatsApp Image 2019-11-23 at 8 47 25 PM](https://user-images.githubusercontent.com/25345637/69488068-99d13600-0e32-11ea-9339-2d660766bc10.jpeg)

**Comment by khoren93** [comment]
Hi @jhlake 
Thanks for your feedback, i added this feature in the project :)
