### ISSUE TITLE
how to use common api response?

### ISSUE THREAD

**Issue by ninjandroid** [khoren93/SwiftHub#3]
In your API you are using models to map api response, How can we have map common api response? for example I have this respse used across all api responses : 
```
{
  "page": 1,
  "results": [
    {
      "poster_path": null,
      "adult": false
   }
  ],
  "total_results": 61,
  "total_pages": 4
}
```

the results object is where we get arrays of objects.

https://developers.themoviedb.org/3/discover/movie-discover

I tried this : ```

 func repositoryEvents(owner: String, repo: String, page: Int) -> Observable<ApiResponse<[Event]>> {
        return provider.request(.repositoryEvents(owner: owner, repo: repo, page: page))
            .mapObject(ApiResponse.self)
            .observeOn(MainScheduler.instance)
    }
```
based on this https://github.com/khoren93/SwiftHub/blob/master/SwiftHub/Networking/Api.swift#L155

but I find myself repeating it over my app. Is there any better way?

**Comment by khoren93** [comment]
I think you need generic object mapping, please check out this example.
https://github.com/tristanhimmelman/ObjectMapper/blob/master/Tests/ObjectMapperTests/GenericObjectsTests.swift
