### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by LwcXing** [khoren93/SwiftHub#30]
Unable to run, has been stalled in compiling

**Comment by jeetdholakia** [comment]
same here, any luck running the app?

**Comment by khoren93** [comment]
Hi @jeetdholakia 
Is the `bundle exec fastlane setup` command finished with success?
Can You provide the log of exception?
Thanks

**Comment by jeetdholakia** [comment]
I couldn't go past the `bundle install` command. It shows the following error

`An error occurred while installing ffi (1.12.2), and Bundler cannot
continue.
Make sure that `gem install ffi -v '1.12.2' --source 'https://rubygems.org/'`
succeeds before bundling.`

I even tried installing ffi separately, which succeeded in installing, but this message doesn't go away.

In the end I just installed the pods and ran the project.

**Comment by jeetdholakia** [comment]
I deleted and cloned the project again and viola! It worked. Followed the exact same steps as last time.
