### ISSUE TITLE
tabbar点击bug问题

### ISSUE THREAD

**Issue by tan-eleph** [khoren93/SwiftHub#37]
**Describe the bug**

**To Reproduce**
1. Go to 'Setting'
2. Click on 'Theme' open status
3. Click on other tabbar 'Theme' status update Not in time

**Comment by khoren93** [comment]
Hi @tan-eleph 
Thanks for an issue, i will try to fix it

**Comment by khoren93** [comment]
@tan-eleph 
fixed, please check out

**Comment by tan-eleph** [comment]
ok, issue close

Khoren Markosyan <notifications@github.com> 于2020年5月18日周一 下午10:52写道：
