### ISSUE TITLE
The use of selected  segment is wrong

### ISSUE THREAD

**Issue by ninjandroid** [khoren93/SwiftHub#4]
in User events, there are 2 segments received and performed. when you tap on received it shows the performed ones instead.and vice versa.

I debugged this line https://github.com/khoren93/SwiftHub/blob/master/SwiftHub/Modules/Events/EventsViewModel.swift#L138 the segment returns **received** when you tap on Performed segment. 

I added  another segment, so we have now 3 segments, it returns wrong segment index each time.

Same for Issues.

**Comment by ninjandroid** [comment]
Nice !
Btw I played with the code to use Collectionview instead of tableview. All seems good but one thing is that when data is empty I can't seem to refresh, altough it is wokring well with tableview. do you know the reason?

**Comment by khoren93** [comment]
Try to set alwaysBounceVertical = true in your collection view.
