### ISSUE TITLE
Wrong version for SwiftLint

### ISSUE THREAD

**Issue by zhangbaiyi** [khoren93/SwiftHub#55]
# Build failure: pod throws "None of your spec sources contain a spec satisfying the dependencies"

**Describe the bug**
Before:
SwiftLint 0.50.3
Now:
SwiftLint 0.53.0
The latest release of SwiftLint is at [0.51.0](https://github.com/realm/SwiftLint)

**To Reproduce**
1. `cd SwiftHub` 
2. `bundle install`
3. `bundle exec fastlane setup`
4. See error (or just run any `pod` commands)

**Expected behavior**
None of your spec sources contain a spec satisfying the dependency: `SwiftLint (= 0.53.0)`.

**Desktop (please complete the following information):**
 - OS: macOS 13.2

**Comment by khoren93** [comment]
Thanks for reporting the wrong version for SwiftLint issue. We've fixed it. Your feedback is appreciated. Let us know if you have more suggestions.
