### ISSUE TITLE
TabBarController Display abnormal

### ISSUE THREAD

**Issue by yangyu92** [khoren93/SwiftHub#8]
HomeTabBarController class When TabBar is switched quickly, the selected item is abnormal, and the wrong position is as follows: NO.1
In addition: TabBar selected item is not normal when switching skin

func makeUI() {
        // Configure tab bar
        hero.isEnabled = true
        tabBar.hero.id = "TabBarID"
        tabBar.isTranslucent = false
       
        -------------- NO.1 ------------
        NotificationCenter.default
            .rx.notification(NSNotification.Name(LCLLanguageChangeNotification))
            .subscribe { [weak self] (event) in
                self?.animatedItems.forEach({ (item) in
                    item.title = HomeTabBarItem(rawValue: item.tag)?.title
                })
                self?.viewControllers = self?.viewControllers
            }.disposed(by: rx.disposeBag)

        themeService.rx
            .bind({ $0.primaryDark }, to: tabBar.rx.barTintColor)
            .disposed(by: rx.disposeBag)
    }

**Comment by khoren93** [comment]
Hi @yangyu92 
I fixed this issue, please check out.
Thanks!
