### ISSUE TITLE
Retry button with DZNEmptyDataSet

### ISSUE THREAD

**Issue by ninjandroid** [khoren93/SwiftHub#9]
**Is your feature request related to a problem? Please describe.**
When device goes offline, it should show a button to retry to perform the action.

**Describe the solution you'd like**
When you go to trendng screen and offline it shows the empty icon, here add a retry button to the empty view

![image](https://user-images.githubusercontent.com/32970250/51905704-d91d2a80-23b9-11e9-9e9b-a8439d462f1a.png)

**Comment by khoren93** [comment]
Hi @ninjandroid 
In offline mode, the application does not send requests, but as soon as the network is connected, the last requests are automatically forwarded (thanks to RxSwift), so there is no need for a retry button :)
